Disable geraldine in fetchmail

diff --git a/fetchmail b/fetchmail
--- a/fetchmail
+++ b/fetchmail
@@ -1,29 +1,29 @@
 #!/bin/bash
 
-MBOX_TMPFILE="$HOME/Maildir/.geraldine_mbox.tmp"
+#MBOX_TMPFILE="$HOME/Maildir/.geraldine_mbox.tmp"
 MAILDIR="$HOME/Maildir"
 
 set -e
 
 function fetchmail()
 {
-    if [[ -s "$MBOX_TMPFILE" ]]; then
-        echo "Running fdm early to process leftover files in $MBOX_TMPFILE"
-        fdm -f "$MAILDIR/fdm.conf" -a "geraldine" fetch
-    fi
-    if [[ -s "$MBOX_TMPFILE" ]]; then
-        echo "ERROR: fdm did not process all messages in $MBOX_TMPFILE" >&2
-        exit 1
-    fi
+    #if [[ -s "$MBOX_TMPFILE" ]]; then
+    #    echo "Running fdm early to process leftover files in $MBOX_TMPFILE"
+    #    fdm -f "$MAILDIR/fdm.conf" -a "geraldine" fetch
+    #fi
+    #if [[ -s "$MBOX_TMPFILE" ]]; then
+    #    echo "ERROR: fdm did not process all messages in $MBOX_TMPFILE" >&2
+    #    exit 1
+    #fi
 
-    echo "Transferring mbox from geraldine.fjfi.cvut.cz"
-    messages=$(ssh geraldine '$HOME/.local/bin/messages -q')
-    if [[ "$messages" != "0" ]]; then
-        # NOTE: movemail supports locking
-        ssh geraldine '$HOME/.local/bin/movemail /var/mail/klinkovsky $HOME/mbox'
-        scp -Cq geraldine:mbox "$MBOX_TMPFILE"
-        ssh geraldine 'rm $HOME/mbox'
-    fi
+    #echo "Transferring mbox from geraldine.fjfi.cvut.cz"
+    #messages=$(ssh geraldine '$HOME/.local/bin/messages -q')
+    #if [[ "$messages" != "0" ]]; then
+    #    # NOTE: movemail supports locking
+    #    ssh geraldine '$HOME/.local/bin/movemail /var/mail/klinkovsky $HOME/mbox'
+    #    scp -Cq geraldine:mbox "$MBOX_TMPFILE"
+    #    ssh geraldine 'rm $HOME/mbox'
+    #fi
 
     fdm -f "$MAILDIR/fdm.conf" fetch
 
