update fetchmail

diff --git a/fetchmail b/fetchmail
--- a/fetchmail
+++ b/fetchmail
@@ -5,32 +5,47 @@ MAILDIR="$HOME/Maildir"
 
 set -e
 
-if [[ -s "$MBOX_TMPFILE" ]]; then
-    echo "Running fdm early to process leftover files in $MBOX_TMPFILE"
-    fdm -f "$MAILDIR/fdm.conf" -a "geraldine" fetch
-fi
-if [[ -s "$MBOX_TMPFILE" ]]; then
-    echo "ERROR: fdm did not process all messages in $MBOX_TMPFILE" >&2
-    exit 1
-fi
+function fetchmail()
+{
+    if [[ -s "$MBOX_TMPFILE" ]]; then
+        echo "Running fdm early to process leftover files in $MBOX_TMPFILE"
+        fdm -f "$MAILDIR/fdm.conf" -a "geraldine" fetch
+    fi
+    if [[ -s "$MBOX_TMPFILE" ]]; then
+        echo "ERROR: fdm did not process all messages in $MBOX_TMPFILE" >&2
+        exit 1
+    fi
 
-echo "Transferring mbox from geraldine.fjfi.cvut.cz"
-messages=$(ssh geraldine '$HOME/.local/bin/messages -q')
-if [[ "$messages" != "0" ]]; then
-    # NOTE: movemail supports locking
-    ssh geraldine '$HOME/.local/bin/movemail /var/mail/klinkovsky $HOME/mbox'
-    scp -Cq geraldine:mbox "$MBOX_TMPFILE"
-    ssh geraldine 'rm $HOME/mbox'
-fi
+    echo "Transferring mbox from geraldine.fjfi.cvut.cz"
+    messages=$(ssh geraldine '$HOME/.local/bin/messages -q')
+    if [[ "$messages" != "0" ]]; then
+        # NOTE: movemail supports locking
+        ssh geraldine '$HOME/.local/bin/movemail /var/mail/klinkovsky $HOME/mbox'
+        scp -Cq geraldine:mbox "$MBOX_TMPFILE"
+        ssh geraldine 'rm $HOME/mbox'
+    fi
 
-count-unread-mails.sh
+    count-unread-mails.sh
 
-fdm -f "$MAILDIR/fdm.conf" fetch
+    fdm -f "$MAILDIR/fdm.conf" fetch
 
-count-unread-mails.sh
+    count-unread-mails.sh
 
-# synchronize with jlk.fjfi.cvut.cz
-if [[ $(uname -n) != *".fjfi.cvut.cz" ]]; then
-    echo "Synchronizing maildir with jlk.fjfi.cvut.cz"
-    unison maildir -batch -silent -log=false
+    # synchronize with jlk.fjfi.cvut.cz
+    if [[ $(uname -n) != *".fjfi.cvut.cz" ]]; then
+        echo "Synchronizing maildir with jlk.fjfi.cvut.cz"
+        unison maildir -batch -silent -log=false
+    fi
+}
+
+if [[ "$1" == "loop" ]]; then
+    # ring a bell when the loop breaks
+    trap "echo $(tput bel)" EXIT
+
+    while true; do
+        fetchmail
+        sleep 1m
+    done
+else
+    fetchmail
 fi
